/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package correccioncalculadora;

import java.util.Scanner;

/**
 *
 * @author jseba
 */
public class Calculadora extends javax.swing.JFrame {

    int opcion, opcion_basicas,opcion_trigo;
    double angulo_grados,angulo_radianes,raiz,potencia,saldo_total,indice,exponente;
    CalculadoraClass operaciones=new CalculadoraClass();
    Scanner asignar=new Scanner (System.in);
    public double primerNumero,segundoNumero, Resultado;
    public  String CadenaNumeros = "";
    public  String Operacion = "nula";
    public boolean Activado = true;
    public boolean punto = true;
    
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton23 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        Num1 = new javax.swing.JButton();
        Num2 = new javax.swing.JButton();
        Num3 = new javax.swing.JButton();
        Num4 = new javax.swing.JButton();
        Num5 = new javax.swing.JButton();
        Num6 = new javax.swing.JButton();
        Num8 = new javax.swing.JButton();
        Num9 = new javax.swing.JButton();
        Num7 = new javax.swing.JButton();
        Num0 = new javax.swing.JButton();
        Signo = new javax.swing.JButton();
        Punto = new javax.swing.JButton();
        Borrar1 = new javax.swing.JButton();
        Potencia = new javax.swing.JButton();
        Raiz = new javax.swing.JButton();
        BorrarTodo = new javax.swing.JButton();
        Sumar = new javax.swing.JButton();
        Restar = new javax.swing.JButton();
        Multiplicar = new javax.swing.JButton();
        Dividir = new javax.swing.JButton();
        Sen = new javax.swing.JButton();
        Cos = new javax.swing.JButton();
        Tan = new javax.swing.JButton();
        Igual = new javax.swing.JButton();
        EtiquetaNumero = new javax.swing.JTextField();
        MostrarNumero = new javax.swing.JTextField();

        jButton10.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        jButton10.setText("8");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        jButton12.setText("0");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        jButton14.setText("+-");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        jButton16.setText("1");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        jButton18.setText("C");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton23.setText("+");
        jButton23.setMaximumSize(new java.awt.Dimension(39, 19));
        jButton23.setMinimumSize(new java.awt.Dimension(39, 19));
        jButton23.setPreferredSize(new java.awt.Dimension(39, 19));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton26.setText("x");
        jButton26.setMaximumSize(new java.awt.Dimension(39, 19));
        jButton26.setMinimumSize(new java.awt.Dimension(39, 19));
        jButton26.setPreferredSize(new java.awt.Dimension(39, 19));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculadora Kadio\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(311, 321));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(311, 297));
        jInternalFrame1.setVisible(true);

        Num1.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Num1.setText("1");
        Num1.setMaximumSize(new java.awt.Dimension(39, 19));
        Num1.setMinimumSize(new java.awt.Dimension(39, 19));
        Num1.setPreferredSize(new java.awt.Dimension(39, 19));
        Num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num1ActionPerformed(evt);
            }
        });

        Num2.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Num2.setText("2");
        Num2.setMaximumSize(new java.awt.Dimension(39, 19));
        Num2.setMinimumSize(new java.awt.Dimension(39, 19));
        Num2.setPreferredSize(new java.awt.Dimension(39, 19));
        Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num2ActionPerformed(evt);
            }
        });

        Num3.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Num3.setText("3");
        Num3.setMaximumSize(new java.awt.Dimension(39, 19));
        Num3.setMinimumSize(new java.awt.Dimension(39, 19));
        Num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num3ActionPerformed(evt);
            }
        });

        Num4.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Num4.setText("4");
        Num4.setMaximumSize(new java.awt.Dimension(39, 19));
        Num4.setMinimumSize(new java.awt.Dimension(39, 19));
        Num4.setPreferredSize(new java.awt.Dimension(39, 19));
        Num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num4ActionPerformed(evt);
            }
        });

        Num5.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Num5.setText("5");
        Num5.setMaximumSize(new java.awt.Dimension(39, 19));
        Num5.setMinimumSize(new java.awt.Dimension(39, 19));
        Num5.setPreferredSize(new java.awt.Dimension(39, 19));
        Num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num5ActionPerformed(evt);
            }
        });

        Num6.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Num6.setText("6");
        Num6.setMaximumSize(new java.awt.Dimension(39, 19));
        Num6.setMinimumSize(new java.awt.Dimension(39, 19));
        Num6.setPreferredSize(new java.awt.Dimension(39, 19));
        Num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num6ActionPerformed(evt);
            }
        });

        Num8.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Num8.setText("8");
        Num8.setMaximumSize(new java.awt.Dimension(39, 19));
        Num8.setMinimumSize(new java.awt.Dimension(39, 19));
        Num8.setPreferredSize(new java.awt.Dimension(39, 19));
        Num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num8ActionPerformed(evt);
            }
        });

        Num9.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Num9.setText("9");
        Num9.setMaximumSize(new java.awt.Dimension(39, 19));
        Num9.setMinimumSize(new java.awt.Dimension(39, 19));
        Num9.setPreferredSize(new java.awt.Dimension(39, 19));
        Num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num9ActionPerformed(evt);
            }
        });

        Num7.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Num7.setText("7");
        Num7.setMaximumSize(new java.awt.Dimension(39, 19));
        Num7.setMinimumSize(new java.awt.Dimension(39, 19));
        Num7.setPreferredSize(new java.awt.Dimension(39, 19));
        Num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num7ActionPerformed(evt);
            }
        });

        Num0.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Num0.setText("0");
        Num0.setMaximumSize(new java.awt.Dimension(39, 19));
        Num0.setMinimumSize(new java.awt.Dimension(39, 19));
        Num0.setPreferredSize(new java.awt.Dimension(39, 19));
        Num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num0ActionPerformed(evt);
            }
        });

        Signo.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Signo.setText("π");
        Signo.setMaximumSize(new java.awt.Dimension(39, 19));
        Signo.setMinimumSize(new java.awt.Dimension(39, 19));
        Signo.setPreferredSize(new java.awt.Dimension(39, 19));
        Signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignoActionPerformed(evt);
            }
        });

        Punto.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Punto.setText(".");
        Punto.setMaximumSize(new java.awt.Dimension(39, 19));
        Punto.setMinimumSize(new java.awt.Dimension(39, 19));
        Punto.setPreferredSize(new java.awt.Dimension(39, 19));
        Punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntoActionPerformed(evt);
            }
        });

        Borrar1.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Borrar1.setText("C");
        Borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar1ActionPerformed(evt);
            }
        });

        Potencia.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Potencia.setText("^");
        Potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotenciaActionPerformed(evt);
            }
        });

        Raiz.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Raiz.setText("√");
        Raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RaizActionPerformed(evt);
            }
        });

        BorrarTodo.setText("CE");
        BorrarTodo.setMaximumSize(new java.awt.Dimension(100, 19));
        BorrarTodo.setMinimumSize(new java.awt.Dimension(100, 19));
        BorrarTodo.setPreferredSize(new java.awt.Dimension(100, 19));
        BorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarTodoActionPerformed(evt);
            }
        });

        Sumar.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Sumar.setText("+");
        Sumar.setMaximumSize(new java.awt.Dimension(47, 19));
        Sumar.setMinimumSize(new java.awt.Dimension(47, 19));
        Sumar.setPreferredSize(new java.awt.Dimension(47, 19));
        Sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumarActionPerformed(evt);
            }
        });

        Restar.setText("-");
        Restar.setMaximumSize(new java.awt.Dimension(47, 19));
        Restar.setMinimumSize(new java.awt.Dimension(47, 19));
        Restar.setPreferredSize(new java.awt.Dimension(47, 19));
        Restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestarActionPerformed(evt);
            }
        });

        Multiplicar.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Multiplicar.setText("x");
        Multiplicar.setMaximumSize(new java.awt.Dimension(47, 19));
        Multiplicar.setMinimumSize(new java.awt.Dimension(47, 19));
        Multiplicar.setPreferredSize(new java.awt.Dimension(47, 19));
        Multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicarActionPerformed(evt);
            }
        });

        Dividir.setText("/");
        Dividir.setMaximumSize(new java.awt.Dimension(47, 19));
        Dividir.setMinimumSize(new java.awt.Dimension(47, 19));
        Dividir.setPreferredSize(new java.awt.Dimension(47, 19));
        Dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DividirActionPerformed(evt);
            }
        });

        Sen.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Sen.setText("Sen");
        Sen.setMaximumSize(new java.awt.Dimension(47, 19));
        Sen.setMinimumSize(new java.awt.Dimension(47, 19));
        Sen.setPreferredSize(new java.awt.Dimension(47, 19));
        Sen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenActionPerformed(evt);
            }
        });

        Cos.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Cos.setText("Cos");
        Cos.setMaximumSize(new java.awt.Dimension(47, 19));
        Cos.setMinimumSize(new java.awt.Dimension(47, 19));
        Cos.setPreferredSize(new java.awt.Dimension(47, 19));
        Cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CosActionPerformed(evt);
            }
        });

        Tan.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Tan.setText("Tan");
        Tan.setMaximumSize(new java.awt.Dimension(47, 19));
        Tan.setMinimumSize(new java.awt.Dimension(47, 19));
        Tan.setPreferredSize(new java.awt.Dimension(47, 19));
        Tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanActionPerformed(evt);
            }
        });

        Igual.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
        Igual.setText("=");
        Igual.setMaximumSize(new java.awt.Dimension(47, 19));
        Igual.setMinimumSize(new java.awt.Dimension(47, 19));
        Igual.setPreferredSize(new java.awt.Dimension(47, 19));
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });

        EtiquetaNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EtiquetaNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        EtiquetaNumero.setMaximumSize(new java.awt.Dimension(190, 2147483647));
        EtiquetaNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtiquetaNumeroActionPerformed(evt);
            }
        });

        MostrarNumero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MostrarNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        MostrarNumero.setMaximumSize(new java.awt.Dimension(190, 2147483647));
        MostrarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EtiquetaNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Num1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Num4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Borrar1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(Num5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Num6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Num2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Potencia))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Raiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Num3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(Num7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(Num8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(Punto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Signo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BorrarTodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Restar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(Sen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(Tan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(MostrarNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(MostrarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EtiquetaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Borrar1)
                    .addComponent(Potencia)
                    .addComponent(Raiz)
                    .addComponent(BorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sumar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Restar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Punto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Signo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num1ActionPerformed
       if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "1";
        }else{
            CadenaNumeros += "1";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_Num1ActionPerformed

    private void Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num2ActionPerformed
        if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "2";
        }else{
            CadenaNumeros += "2";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_Num2ActionPerformed

    private void Num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num3ActionPerformed
          if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "3";
        }else{
            CadenaNumeros += "3";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_Num3ActionPerformed

    private void Num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num4ActionPerformed
          if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "4";
        }else{
            CadenaNumeros += "4";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_Num4ActionPerformed

    private void Num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num5ActionPerformed
          if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "5";
        }else{
            CadenaNumeros += "5";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_Num5ActionPerformed

    private void Num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num6ActionPerformed
          if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "6";
        }else{
            CadenaNumeros += "6";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_Num6ActionPerformed

    private void Num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num8ActionPerformed
         if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "8";
        }else{
            CadenaNumeros += "8";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_Num8ActionPerformed

    private void Num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num9ActionPerformed
         if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "9";
        }else{
            CadenaNumeros += "9";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_Num9ActionPerformed

    private void Num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num7ActionPerformed
          if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "7";
        }else{
            CadenaNumeros += "7";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_Num7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
          if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "10";
        }else{
            CadenaNumeros += "10";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_jButton10ActionPerformed

    private void Num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num0ActionPerformed
         if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "0";
        }else{
            CadenaNumeros += "0";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_Num0ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void SignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignoActionPerformed
        if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "3,1416";
        }else{
            CadenaNumeros += "3,1416";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_SignoActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void PuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntoActionPerformed
         if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = ".";
        }else{
            CadenaNumeros += ".";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_PuntoActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void Borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Borrar1ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void PotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotenciaActionPerformed
        if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "^";
        }else{
            CadenaNumeros += "^";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_PotenciaActionPerformed

    private void RaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RaizActionPerformed
          if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "√";
        }else{
            CadenaNumeros += "";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_RaizActionPerformed

    private void SumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumarActionPerformed
       if(Activado == true){
           primerNumero = Double.parseDouble(CadenaNumeros);
           primerNumero=asignar.nextDouble();
           MostrarNumero.setText(CadenaNumeros + " + ");
           CadenaNumeros = "";
           Operacion = "Sumar";
           
           Activado = false;
           
       }
    }//GEN-LAST:event_SumarActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void RestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestarActionPerformed
          if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "-";
        }else{
            CadenaNumeros += "-";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_RestarActionPerformed

    private void MultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicarActionPerformed
          if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "*";
        }else{
            CadenaNumeros += "*";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_MultiplicarActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void DividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DividirActionPerformed
        if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "/";
        }else{
            CadenaNumeros += "/";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_DividirActionPerformed

    private void SenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenActionPerformed
        if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "Sen(";
        }else{
            CadenaNumeros += "Sen(";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_SenActionPerformed

    private void CosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CosActionPerformed
        if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "Cos(";
        }else{
            CadenaNumeros += "Cos(";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_CosActionPerformed

    private void TanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanActionPerformed
        if(EtiquetaNumero.getText().equals("0")){
            CadenaNumeros = "Tan(";
        }else{
            CadenaNumeros += "Tan(";
        } 
        EtiquetaNumero.setText(CadenaNumeros);
        Activado = true;
    }//GEN-LAST:event_TanActionPerformed

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
    if(Operacion.equals("Sumar")){
        segundoNumero = Double.parseDouble(CadenaNumeros);
        segundoNumero=asignar.nextDouble();
        operaciones.Suma(primerNumero,segundoNumero);
        CadenaNumeros = String.valueOf(Resultado);
        EtiquetaNumero.setText(CadenaNumeros);
    }
    MostrarNumero.setText("");
    
    }//GEN-LAST:event_IgualActionPerformed

    private void EtiquetaNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtiquetaNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EtiquetaNumeroActionPerformed

    private void BorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarTodoActionPerformed
        EtiquetaNumero.setText("");
        MostrarNumero.setText("");
    }//GEN-LAST:event_BorrarTodoActionPerformed

    private void MostrarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar1;
    private javax.swing.JButton BorrarTodo;
    private javax.swing.JButton Cos;
    private javax.swing.JButton Dividir;
    private javax.swing.JTextField EtiquetaNumero;
    private javax.swing.JButton Igual;
    private javax.swing.JTextField MostrarNumero;
    private javax.swing.JButton Multiplicar;
    private javax.swing.JButton Num0;
    private javax.swing.JButton Num1;
    private javax.swing.JButton Num2;
    private javax.swing.JButton Num3;
    private javax.swing.JButton Num4;
    private javax.swing.JButton Num5;
    private javax.swing.JButton Num6;
    private javax.swing.JButton Num7;
    private javax.swing.JButton Num8;
    private javax.swing.JButton Num9;
    private javax.swing.JButton Potencia;
    private javax.swing.JButton Punto;
    private javax.swing.JButton Raiz;
    private javax.swing.JButton Restar;
    private javax.swing.JButton Sen;
    private javax.swing.JButton Signo;
    private javax.swing.JButton Sumar;
    private javax.swing.JButton Tan;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton26;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
